export const profiles = [
  {
    id: 1,
    name: 'Andres',
    eyes: 'black',
    mouth: 'big',
    skin: 'brown',
    nose: 'big',
    ear: 'little',
    gender: 'male',
    imgUrl: 'assets/andres.png',
  },
  {
    id: 2,
    name: 'Cristian',
    eyes: 'black',
    mouth: 'middle',
    skin: 'white',
    nose: 'big',
    ear: 'little',
    gender: 'male',
    imgUrl: 'assets/cristian.png',
  },
  {
    id: 3,
    name: 'Camilo',
    eyes: 'black',
    mouth: 'little',
    skin: 'white',
    nose: 'big',
    ear: 'big',
    gender: 'male',
    imgUrl: 'assets/camilo.png',
  },
  {
    id: 4,
    name: 'Ivan',
    eyes: 'brown',
    mouth: 'big',
    skin: 'white',
    nose: 'middle',
    ear: 'none',
    gender: 'male',
    imgUrl: 'assets/ivan.png',
  },
  {
    id: 5,
    name: 'Sergio',
    eyes: 'black',
    mouth: 'little',
    skin: 'white',
    nose: 'little',
    ear: 'middle',
    gender: 'male',
    imgUrl: 'assets/sergio.png',
  },
];
