export const questions = [
  {
    q: 'Es de tes oscura?',
    camilo: 0,
    ivan: 0,
    cristian: 0,
    sergio: 1,
    andres: 1,
  },
  {
    q: 'Es de tes clara',
    camilo: 1,
    ivan: 1,
    cristian: 1,
    sergio: 0,
    andres: 0,
  },
  {
    q: '¿Quien tiene el cabello corto?',
    camilo: 1,
    ivan: 0,
    cristian: 1,
    sergio: 1,
    andres: 1,
  },
  {
    q: '¿A quién se le va la luz?',
    camilo: 1,
    ivan: 0,
    cristian: 0,
    sergio: 1,
    andres: 1,
  },
  {
    q: '¿Quien come coco?',
    camilo: 0,
    ivan: 1,
    cristian: 0,
    sergio: 1,
    andres: 1,
  },
];
